use RPG;

CREATE TABLE STATYSTYKI (
	id int IDENTITY(1,1) PRIMARY KEY,
	poziom int NOT NULL,
	si³a int NOT NULL, 
	zrêcznoœæ int NOT NULL,
	szczêœcie int NOT NULL);
 
CREATE TABLE ISTOTA (
	id int IDENTITY(1,1) PRIMARY KEY,
	nazwa varchar(40) NOT NULL,
	cytat TEXT NOT NULL, 
	historia TEXT NOT NULL,
	p³eæ char(1) CHECK(p³eæ IN ('K','M')) NOT NULL,
	wiek int CHECK(wiek > 0 AND wiek < 400),
	staty int REFERENCES STATYSTYKI ON DELETE CASCADE NOT NULL);
 
CREATE TABLE PRZEDMIOTY (
	id int IDENTITY(1,1) PRIMARY KEY,
	nazwa varchar(40) NOT NULL,
	wartoœæ int NOT NULL,
	staty int REFERENCES STATYSTYKI ON DELETE CASCADE NOT NULL UNIQUE);
 
CREATE TABLE PRZEDMIOTY_ISTOTY (
	id int IDENTITY(1,1) PRIMARY KEY,
	przedmiot int REFERENCES PRZEDMIOTY,
	istota int REFERENCES ISTOTA);
 
CREATE TABLE UMIEJÊTNOŒCI (
	nazwa varchar(60) PRIMARY KEY NOT NULL,
	poziom int NOT NULL,
	obra¿enia int NOT NULL);
 
CREATE TABLE LOKALIZACJA (
	nazwa varchar(60) PRIMARY KEY NOT NULL,
	klimat char(1) CHECK(klimat IN ('P','Z','U')) NOT NULL,
	d³ugoœæ int NOT NULL,
	szerokoœæ int NOT NULL);
 
CREATE TABLE POSTACI(
	[login] varchar(32) NOT NULL,
	id int IDENTITY(1,1)  PRIMARY KEY,
	istota int REFERENCES ISTOTA ON DELETE CASCADE NOT NULL UNIQUE);
 
CREATE TABLE NPC(
	id int IDENTITY(1,1)  PRIMARY KEY,
	istota int REFERENCES ISTOTA ON DELETE CASCADE NOT NULL UNIQUE,
	nazwaUmiejetnosci varchar(60) REFERENCES UMIEJÊTNOŒCI NULL,
	nazwaLokalizacji varchar(60) REFERENCES LOKALIZACJA NOT NULL);
 
CREATE TABLE PRZECIWNICY(
	id int IDENTITY(1,1)  PRIMARY KEY,
	istota int REFERENCES ISTOTA ON DELETE CASCADE NOT NULL UNIQUE,
	nazwaLokalizacji varchar(60) REFERENCES LOKALIZACJA);
 
CREATE TABLE UMIEJÊTNOŒCI_POSTACI (
	postaæ int FOREIGN KEY REFERENCES POSTACI,
	umiejêtnoœæ varchar(60) FOREIGN KEY REFERENCES UMIEJÊTNOŒCI,
	PRIMARY KEY(postaæ, umiejêtnoœæ));
	
/*L - Lokalizacja, N - NPC, P - Przeciwnik*/
CREATE TABLE ZADANIA (
	nazwa varchar(60) PRIMARY KEY NOT NULL,
	cel char(1) CHECK(cel IN ('L','N','P')) NOT NULL,
	npc int REFERENCES NPC);
 
CREATE TABLE MISJE (
	zadanie varchar(60) PRIMARY KEY REFERENCES ZADANIA ON DELETE CASCADE NOT NULL);
 
CREATE TABLE ZLECENIA (
	zadanie varchar(60) PRIMARY KEY REFERENCES ZADANIA ON DELETE CASCADE NOT NULL,
	iloœæPrzeciwników int NOT NULL);
 
CREATE TABLE CEL_ZLECENIA (
	zlecenie varchar(60) REFERENCES ZLECENIA,
	przeciwnik int REFERENCES PRZECIWNICY ON DELETE CASCADE,
	PRIMARY KEY(zlecenie, przeciwnik));
 
CREATE TABLE ZADANIA_POSTACI (
	zadanie varchar(60) REFERENCES ZADANIA,
	postaæ int REFERENCES POSTACI,
	PRIMARY KEY(zadanie, postaæ));
 
CREATE TABLE NAGRODA_ZA_ZADANIE (
	zadanie varchar(60) REFERENCES ZADANIA,
	przedmiot int REFERENCES PRZEDMIOTY,
	PRIMARY KEY(zadanie, przedmiot));

ALTER TABLE MISJE
	ADD dodatkoweInformacje TEXT NOT NULL;