use RPG;

DROP TABLE NAGRODA_ZA_ZADANIE
DROP TABLE ZADANIA_POSTACI
DROP TABLE CEL_ZLECENIA
DROP TABLE ZLECENIA
DROP TABLE MISJE
DROP TABLE ZADANIA
DROP TABLE UMIEJÊTNOŒCI_POSTACI
DROP TABLE PRZECIWNICY
DROP TABLE NPC
DROP TABLE POSTACI
DROP TABLE LOKALIZACJA
DROP TABLE UMIEJÊTNOŒCI
DROP TABLE PRZEDMIOTY_ISTOTY
DROP TABLE PRZEDMIOTY
DROP TABLE ISTOTA
DROP TABLE STATYSTYKI